use core::constants::CT_COMPANION;

struct Know {
    word: [&'static str; 20],
    value: i32,
    area: i32,
    temp: i32,
    answer: &'static str,
    special: i32,
}

const HEALTH: i32 = 1;
const SHOP: i32 = 2;
const GREET: i32 = 3;
const WHOAMI: i32 = 4;
const WHERE: i32 = 5;
const STOP: i32 = 6;
const MOVE: i32 = 7;
const ATTACK: i32 = 8;
const WAIT: i32 = 9;
const FOLLOW: i32 = 10;
const TIME: i32 = 11;
const POINTS: i32 = 12;
const BUYGOLD: i32 = 13;
const BUYHEALTH: i32 = 14;
const BUYMANA: i32 = 15;
const BUYEXP: i32 = 16;
const TRANSFER: i32 = 17;
const SPELLINFO: i32 = 18;
const QUIET: i32 = 19;

const AR_GENERAL: i32 = 0;
const AR_THIEF: i32 = 1;
const AR_CASTLE: i32 = 2;
const AR_GROLM: i32 = 3;
const AR_ASTON: i32 = 4; // locations in aston
const AR_THIEF2: i32 = 5;
const AR_TOMB: i32 = 6;
const AR_JOE: i32 = 7;
const AR_PURPLE: i32 = 8;
const AR_SLORD: i32 = 9;
const AR_OUTLAW: i32 = 10;
const AR_MMAZE: i32 = 11;
const AR_LIZARD: i32 = 12;
const AR_UNDER_I: i32 = 13;
const AR_KNIGHT: i32 = 14;
const AR_MINE: i32 = 15;
const AR_STRONGHOLD: i32 = 16;
const AR_NEST: i32 = 17;

/* keep these in tune with RIDDLE_MIN_AREA/RIDDLE_MAX_AREA in Lab9.h! */
const AR_RIDDLE1: i32 = 21;
const AR_RIDDLE2: i32 = 22;
const AR_RIDDLE3: i32 = 23;
const AR_RIDDLE4: i32 = 24;
const AR_RIDDLE5: i32 = 25;
const RIDDLE_TEXT: &str = "If you bring me the right volume of the Book of Wisdom, I will tell you a riddle. To answer the riddle, just say the word the riddle asks for. If you answer correctly, I will bring you to the next stage of your quest.\n";

const AR_ALL: i32 = 12345;

const KNOW: [Know; 227] = [
    Know {
        word: ["!where", "!tavern", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The tavern lies in the north part of the city, on Temple Street.",
        special: 0,
    },
    Know {
        word: ["!where", "!thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Thieves House is located at the east end of Temple Street.",
        special: 0,
    },
    Know {
        word: ["!where", "?haunted", "!castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Haunted Castle is in the south-east corner of the city, on Castle Way.",
        special: 0,
    },
    Know {
        word: ["!where", "?cursed", "!tomb", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Cursed Tomb is in the north-east corner of the city, on Rose Street.",
        special: 0,
    },
    Know {
        word: ["!where", "!joe", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "Joe's House is in the middle of Castle Way.",
        special: 0,
    },
    Know {
        word: ["!where", "?skeleton", "!lord", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Skeleton Lord is in the dark, large building in the middle of Merchants Way.",
        special: 0,
    },
    Know {
        word: ["!where", "?templar", "!outlaw", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Templar Outlaws live in a fortified building in the south-west corner of Aston.",
        special: 0,
    },
    Know {
        word: ["!where", "?magic", "!maze", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Magic Maze is in the north-west corner of Aston.",
        special: 0,
    },
    Know {
        word: ["!where", "!labyrinth", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The entrance to the Labyrinth is in the middle of Merchants Way.",
        special: 0,
    },
    Know {
        word: ["!where", "!random", "?dungeon", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The entrance to the Random Dungeon is in the middle of Merchants Way.",
        special: 0,
    },
    Know {
        word: ["!where", "!bank", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The bank is in the north west corner of thy city, on Temple Street.",
        special: 0,
    },
    Know {
        word: ["!where", "!shop", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "Most shops are on Merchants Way.",
        special: 0,
    },
    Know {
        word: ["!where", "!buy", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "Most shops are on Merchants Way.",
        special: 0,
    },
    Know {
        word: ["!have", "!no", "!money", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "You might find some valuable stuff in the Donations Room in one of the temples.",
        special: 0,
    },
    Know {
        word: ["!where", "!temple", "!street", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Temple Street is in the northern part of the city. It goes from the east to the west end of Aston.",
        special: 0,
    },
    Know {
        word: ["!where", "!castle", "!way", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Temple Street is in the south-east corner of the city.",
        special: 0,
    },
    Know {
        word: ["!where", "!south", "!end", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "South End? That's a street in the south-west corner of Aston.",
        special: 0,
    },
    Know {
        word: ["!where", "!rose", "!street", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "Rose Street is on the eastern border of the city.",
        special: 0,
    },
    Know {
        word: ["!where", "!merchant", "!way", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Merchants Way divides the city in the middle. It goes from north to south.",
        special: 0,
    },
    Know {
        word: ["!where", "!new", "!street", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "New Street is on the western border of Aston.",
        special: 0,
    },
    Know {
        word: ["?where", "?what", "!aston", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "This city is called Aston. But you should know that!",
        special: 0,
    },
    Know {
        word: ["!where", "!temple", "?skua", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The Temple of Skua is in the eastern part of Temple Street.",
        special: 0,
    },
    Know {
        word: ["!where", "!jamil", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "Jamil lives on Temple Street, a bit east of the Temple of Skua.",
        special: 0,
    },
    Know {
        word: ["!who", "!jamil", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "Jamil? He's a merchant. Rumor has it he has some connections to the thieves.",
        special: 0,
    },
    Know {
        word: ["!where", "!sirjan", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "Sirjan lives on Merchants Way. Fairly close to Damor's Shop.",
        special: 0,
    },
    Know {
        word: ["!where", "!damor", "?shop", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "Damor's Magic Shop? It's on Merchants Way.",
        special: 0,
    },
    Know {
        word: ["!who", "!damor", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 5,
        area: AR_ASTON,
        temp: 0,
        answer: "Damor came into Aston about 60 years ago. Noboby knows where he came from. He is very powerful, so no one dared to ask.",
        special: 0,
    },
    Know {
        word: ["!tell", "!damor", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 5,
        area: AR_ASTON,
        temp: 0,
        answer: "Damor came into Aston about 60 years ago. Noboby knows where he came from. He is very powerful, so no one dared to ask.",
        special: 0,
    },
    Know {
        word: ["!ratling", "?eye", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "You'd best ask Robin about that. He lives on South End.",
        special: 0,
    },
    Know {
        word: ["!underground", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "You'd best ask Robin about that. He lives on South End.",
        special: 0,
    },
    Know {
        word: ["!azrael", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "You'd best ask Robin about that. He lives on South End.",
        special: 0,
    },
    Know {
        word: ["!where", "!mine", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "The mine is north of the Temple of Skua.",
        special: 0,
    },
    Know {
        word: ["?what", "?where", "?good", "!start", "?place", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "A good place to start your adventurer's life? You'd best talk to Jamil.",
        special: 0,
    },
    Know {
        word: ["?tell", "?where", "?good", "!start", "?place", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_ASTON,
        temp: 0,
        answer: "A good place to start your adventurer's life? You'd best talk to Jamil.",
        special: 0,
    },
    Know {
        word: ["!where", "!thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_THIEF,
        temp: 25,
        answer: "The Thieves House is located at the east end of Temple Street.",
        special: 0,
    },
    Know {
        word: ["!where", "?thief", "!house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_THIEF,
        temp: 25,
        answer: "The Thieves House is located at the east end of Temple Street.",
        special: 0,
    },
    Know {
        word: ["!locked", "!door", "!thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF,
        temp: 25,
        answer: "There are two locked doors in the Thieves House. For the first, you'll easily find the key.",
        special: 0,
    },
    Know {
        word: ["!second", "!door", "!thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF,
        temp: 25,
        answer: "The second locked door in the Thieves House? Don't go there!.",
        special: 0,
    },
    Know {
        word: ["!danger", "!thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF,
        temp: 25,
        answer: "What would you expect in the Thieves' House? Thieves of course. They're very poor fighters.",
        special: 0,
    },
    Know {
        word: ["!tell", "!thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF,
        temp: 25,
        answer: "What would you expect in the Thieves' House? Thieves of course. They're very poor fighters.",
        special: 0,
    },
    Know {
        word: ["!who", "!thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF,
        temp: 25,
        answer: "What would you expect in the Thieves' House? Thieves of course. They're very poor fighters.",
        special: 0,
    },
    Know {
        word: ["!why", "", "?want", "!amulet", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF,
        temp: 25,
        answer: "The thieves stole my amulet. I want it back.",
        special: 0,
    },
    Know {
        word: ["!what", "!amulet", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF,
        temp: 25,
        answer: "It's just a small, golden amulet.",
        special: 0,
    },
    Know {
        word: ["!tell", "!amulet", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF,
        temp: 25,
        answer: "It's just a small, golden amulet.",
        special: 0,
    },
    Know {
        word: ["!where", "?haunted", "!castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_CASTLE,
        temp: 28,
        answer: "The Haunted Castle is in the south-east corner of the city, on Castle Way.",
        special: 0,
    },
    Know {
        word: ["!locked", "!door", "?haunted", "?castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_CASTLE,
        temp: 28,
        answer: "My guess is that you'll have to find the keys for the locked doors in the Haunted Castle, %s.",
        special: 0,
    },
    Know {
        word: ["!key", "?haunted", "?castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_CASTLE,
        temp: 28,
        answer: "Not all walls are what they seem to be in the Haunted Castle, %s.",
        special: 0,
    },
    Know {
        word: ["!danger", "?haunted", "?castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_CASTLE,
        temp: 28,
        answer: "There are ghosts in the Haunted Castle. They'll curse you! It takes a Corporal to survive that.",
        special: 0,
    },
    Know {
        word: ["!tell", "?haunted", "?castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_CASTLE,
        temp: 28,
        answer: "There are ghosts in the Haunted Castle. They'll curse you! It takes a Corporal to survive that.",
        special: 0,
    },
    Know {
        word: ["!who", "!in", "?haunted", "?castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_CASTLE,
        temp: 28,
        answer: "There are ghosts in the Haunted Castle. They'll curse you! It takes a Corporal to survive that.",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "!belt", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_CASTLE,
        temp: 28,
        answer: "I need the belt for my research.",
        special: 0,
    },
    Know {
        word: ["!what", "!belt", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_CASTLE,
        temp: 28,
        answer: "It's a golden belt with a magical enchantment.",
        special: 0,
    },
    Know {
        word: ["!tell", "!belt", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_CASTLE,
        temp: 28,
        answer: "It's a golden belt with a magical enchantment.",
        special: 0,
    },
    Know {
        word: ["!where", "?cursed", "!tomb", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_TOMB,
        temp: 50,
        answer: "The Cursed Tomb is in the north-east corner of the city, on Rose Street.",
        special: 0,
    },
    Know {
        word: ["!where", "!ruby", "?cursed", "?tomb", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_TOMB,
        temp: 50,
        answer: "The ruby is in a hidden area in the Cursed Tomb.",
        special: 0,
    },
    Know {
        word: ["!how", "!hidden", "?cursed", "?tomb", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_TOMB,
        temp: 50,
        answer: "There are some illusionary walls in the Cursed Tomb.",
        special: 0,
    },
    Know {
        word: ["!danger", "?cursed", "?tomb", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_TOMB,
        temp: 50,
        answer: "The Cursed Tomb is inhibitated by skeletons. They're poor fighters, but you need strong armor to survive their magic.",
        special: 0,
    },
    Know {
        word: ["!tell", "?cursed", "?tomb", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_TOMB,
        temp: 50,
        answer: "The Cursed Tomb is inhibitated by skeletons. They're poor fighters, but you need strong armor to survive their magic.",
        special: 0,
    },
    Know {
        word: ["!who", "!in", "?cursed", "?tomb", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_TOMB,
        temp: 50,
        answer: "The Cursed Tomb is inhibitated by skeletons. They're poor fighters, but you need strong armor to survive their magic.",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "!ruby", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_TOMB,
        temp: 50,
        answer: "The ruby will help me with my magical experiments.",
        special: 0,
    },
    Know {
        word: ["!what", "!ruby", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_TOMB,
        temp: 50,
        answer: "It's a gem with magical properties. Rubies are used to build magical items.",
        special: 0,
    },
    Know {
        word: ["!tell", "!ruby", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_TOMB,
        temp: 50,
        answer: "It's a gem with magical properties. Rubies are used to build magical items.",
        special: 0,
    },
    Know {
        word: ["!where", "!joe", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_JOE,
        temp: 64,
        answer: "Joe's House is in the middle of Castle Way.",
        special: 0,
    },
    Know {
        word: ["!danger", "?joe", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_JOE,
        temp: 64,
        answer: "It might be wise to assure that Joe will not get any help when you attack him.",
        special: 0,
    },
    Know {
        word: ["!tell", "?joe", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_JOE,
        temp: 64,
        answer: "It might be wise to assure that Joe will not get any help when you attack him.",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "?bronze", "!armor",         "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_JOE,
        temp: 64,
        answer: "The bronze armor was a gift from my father. Joe stole it.",
        special: 0,
    },
    Know {
        word: ["!what", "?bronze", "!armor",         "?", "",  "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_JOE,
        temp: 64,
        answer: "The bronze armor was a gift from my father. Joe stole it.",
        special: 0,
    },
    Know {
        word: ["!tell", "?bronze", "!armor",         "?", "",  "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_JOE,
        temp: 64,
        answer: "The bronze armor was a gift from my father. Joe stole it.",
        special: 0,
    },
    Know {
        word: ["?black", "!stronghold", "!coin", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_STRONGHOLD,
        temp: 72,
        answer: "Bring me one of the black candles from the Stronghold, and I'll give you the star part of the coin.",
        special: 0,
    },
    Know {
        word: ["!help", "?need", "?stronghold", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "Every few hours a horde of monsters from the Black Stronghold is attacking our outpost or the city entrance. If you could help PROTECT these places, or - even better - enter the STRONGHOLD and stop the monsters, we'd reward you.",
        special: 0,
    },
    Know {
        word: ["!protect", "?outpost", "?city", "?entrance", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "Wait close to one of these points till the guards there shout alert. Then help them in the fight. They'll report your success and you can collect your REWARD here afterwards.",
        special: 0,
    },
    Know {
        word: ["!reward", "?protect", "?city", "?stronghold", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "Depending on your success you will get money, potions or experience. Ask about your POINTS...",
        special: 0,
    },
    Know {
        word: ["!stronghold", "?enter", "?attack", "?black", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "The monsters are coming from the Black Stronghold. Some evil magic is creating them. As far as we know, this magic needs black candles. So if you can bring us some black candles we will know you were successful and REWARD you.",
        special: 0,
    },
    Know {
        word: ["!points", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "You have %d points. You can BUY GOLD at one coin per point, BUY HEALING potions for 6 points, BUY MANA potions for 9 points or BUY EXPERIENCE at %d exp per point.",
        special: POINTS,
    },
    Know {
        word: ["!buy", "!gold", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "",
        special: BUYGOLD,
    },
    Know {
        word: ["!buy", "!health", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "",
        special: BUYHEALTH,
    },
    Know {
        word: ["!buy", "!healing", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "",
        special: BUYHEALTH,
    },
    Know {
        word: ["!buy", "!mana", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "",
        special: BUYMANA,
    },
    Know {
        word: ["!buy", "!exp", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_STRONGHOLD,
        temp: 518,
        answer: "",
        special: BUYEXP,
    },
    Know {
        word: ["!where", "!mine", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_MINE,
        temp: 0,
        answer: "The mine is north of the Temple of Skua.",
        special: 0,
    },
    Know {
        word: ["!danger", "!mine", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_MINE,
        temp: 0,
        answer: "Mining can be dangerous. Place supporting beams to prevent it from collapsing. And don't go into the lower levels too early.",
        special: 0,
    },
    Know {
        word: ["!tell", "!mine", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_MINE,
        temp: 0,
        answer: "The mine was opened only a few years ago. At first, it was a very profitable business. But the workers fled when some of them were killed by skeletons.",
        special: 0,
    },
    Know {
        word: ["!where", "?skeleton", "!lord", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_SLORD,
        temp: 90,
        answer: "The Skeleton Lord is in the dark, large building in the middle of Merchants Way.",
        special: 0,
    },
    Know {
        word: ["!where", "!potion", "?skeleton", "?lord", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_SLORD,
        temp: 90,
        answer: "The potion the Skeleton Lord has could be in a hidden area.",
        special: 0,
    },
    Know {
        word: ["!danger", "?skeleton", "?lord", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_SLORD,
        temp: 90,
        answer: "The Skeleton Lord still has some guards who will protect him. A bold Sergeant should be able to kill them.",
        special: 0,
    },
    Know {
        word: ["!tell", "?skeleton", "?lord", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_SLORD,
        temp: 90,
        answer: "The Skeleton Lord still has some guards who will protect him. A bold Sergeant should be able to kill them.",
        special: 0,
    },
    Know {
        word: ["!who", "!in", "?skeleton", "?lord", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_SLORD,
        temp: 90,
        answer: "The Skeleton Lord still has some guards who will protect him. A bold Sergeant should be able to kill them.",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "!potion", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_SLORD,
        temp: 90,
        answer: "I created the potion when the lord was still alive. Now that he turned into a skeleton, he has no more need for it.",
        special: 0,
    },
    Know {
        word: ["!what", "!potion", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_SLORD,
        temp: 90,
        answer: "It's a greater healing potion. I created the potion when the lord was still alive.",
        special: 0,
    },
    Know {
        word: ["!tell", "!potion", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_SLORD,
        temp: 90,
        answer: "It's a greater healing potion. I created the potion when the lord was still alive.",
        special: 0,
    },
    Know {
        word: ["!where", "?templar", "!outlaw", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_OUTLAW,
        temp: 91,
        answer: "The Templar Outlaws live in a fortified building in the south-west corner of Aston.",
        special: 0,
    },
    Know {
        word: ["!danger", "?templar", "?outlaw", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_OUTLAW,
        temp: 91,
        answer: "The Templar Outlaws are very skilled fighters, and there are many of them. A Staff Sergeant could try to attack them.",
        special: 0,
    },
    Know {
        word: ["!tell", "?templar", "?outlaw", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_OUTLAW,
        temp: 91,
        answer: "The Templar Outlaws are very skilled fighters, and there are many of them. A Staff Sergeant could try to attack them.",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "?barbarian", "!sword", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_OUTLAW,
        temp: 91,
        answer: "It's a good weapon. I like it. And the templars are outlaws, taking from them is not stealing...",
        special: 0,
    },
    Know {
        word: ["!what", "?barbarian", "!sword", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_OUTLAW,
        temp: 91,
        answer: "The barbarian sword is an old weapon. It was made by an now extinct race of barbarians.",
        special: 0,
    },
    Know {
        word: ["!tell", "?barbarian", "!sword", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_OUTLAW,
        temp: 91,
        answer: "The barbarian sword is an old weapon. It was made by an now extinct race of barbarians.",
        special: 0,
    },
    Know {
        word: ["?second", "!door", "?thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF2,
        temp: 107,
        answer: "The second locked door in the Thieves House? You might have to pick the lock.",
        special: 0,
    },
    Know {
        word: ["!danger", "?thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF2,
        temp: 107,
        answer: "Be careful behind the second locked door in the Thieves House. The thieves there know how to fight.",
        special: 0,
    },
    Know {
        word: ["!tell", "?thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF2,
        temp: 107,
        answer: "Be careful behind the second locked door in the Thieves House. The thieves there know how to fight.",
        special: 0,
    },
    Know {
        word: ["!who", "?thief", "?house", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF2,
        temp: 107,
        answer: "Be careful behind the second locked door in the Thieves House. The thieves there know how to fight.",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "?ruby", "!amulet", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF2,
        temp: 107,
        answer: "The Ruby Amulet belongs to me. A few days after I showed it to Jamil it vanished. I'm sure the thieves took it.",
        special: 0,
    },
    Know {
        word: ["!what", "?ruby", "!amulet", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF2,
        temp: 107,
        answer: "It's a small golden amulet with a big ruby on it. It increases your ability to cast magic spells.",
        special: 0,
    },
    Know {
        word: ["!tell", "?ruby", "!amulet", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_THIEF2,
        temp: 107,
        answer: "It's a small golden amulet with a big ruby on it. It increases your ability to cast magic spells.",
        special: 0,
    },
    Know {
        word: ["!where", "?magic", "!maze", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_MMAZE,
        temp: 108,
        answer: "The Magic Maze is in the north-west corner of Aston.",
        special: 0,
    },
    Know {
        word: ["!danger", "?magic", "?maze", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_MMAZE,
        temp: 108,
        answer: "The Magic Maze is full of traps. Be careful and look for all clues you can get. There's also a powerful sorceress you will have to fight.",
        special: 0,
    },
    Know {
        word: ["!tell", "?magic", "?maze", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_MMAZE,
        temp: 108,
        answer: "The Magic Maze is full of traps. Be careful and look for all clues you can get. There's also a powerful sorceress you will have to fight.",
        special: 0,
    },
    Know {
        word: ["!who", "?magic", "?maze", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_MMAZE,
        temp: 108,
        answer: "The Magic Maze is full of traps. Be careful and look for all clues you can get. There's also a powerful sorceress you will have to fight.",
        special: 0,
    },
    Know {
        word: ["!tell", "sorceress", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_MMAZE,
        temp: 108,
        answer: "The sorceress is called Jane. I don't know much about her, only that she killed a few people who survived her maze.",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "!potion", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_MMAZE,
        temp: 108,
        answer: "It's a very strong mana potion and I need it to complete a certain magic spell I've been studying for several years now.",
        special: 0,
    },
    Know {
        word: ["!what", "!potion", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_MMAZE,
        temp: 108,
        answer: "It's a very strong mana potion.",
        special: 0,
    },
    Know {
        word: ["!tell", "!potion", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 25,
        area: AR_MMAZE,
        temp: 108,
        answer: "It's a very strong mana potion.",
        special: 0,
    },
    Know {
        word: ["!where", "?stone", "!sword", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "Now where was that damn stone? Let me think. Ah! I remember. It's over there, in that corner.",
        special: 0,
    },
    Know {
        word: ["!where", "!stone", "?sword", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "Now where was that damn stone? Let me think. Ah! I remember. It's over there, in that corner.",
        special: 0,
    },
    Know {
        word: ["?too", "?weak", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "If you're not strong enough to take the sword now, you might need some form of enchantment. Why not go to Damor's Shop and see if he can help?",
        special: 0,
    },
    Know {
        word: ["?not", "?strong", "?enough", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "If you're not strong enough to take the sword now, you might need some form of enchantment. Why not go to Damor's Shop and see if he can help?",
        special: 0,
    },
    Know {
        word: ["?how", "!take", "!sword", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "If you're not strong enough to take the sword now, you might need some form of enchantment. Why not go to Damor's Shop and see if he can help?",
        special: 0,
    },
    Know {
        word: ["?how", "!get", "!sword", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "If you're not strong enough to take the sword now, you might need some form of enchantment. Why not go to Damor's Shop and see if he can help?",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "?stone", "!sword", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "I've been staring at this stone for years. Can't you imagine I want the matter settled so I can throw the damn stone away?",
        special: 0,
    },
    Know {
        word: ["!what", "?stone", "!sword", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "The sword in the stone in that corner.",
        special: 0,
    },
    Know {
        word: ["!tell", "?stone", "!sword", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 109,
        answer: "The sword in the stone in that corner.",
        special: 0,
    },
    Know {
        word: ["!how", "?create", "?mix", "?potion", "?life", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 111,
        answer: "If I knew how to mix the Potion of Life, I'd do it myself. All I can tell you is that you need three rare flowers.",
        special: 0,
    },
    Know {
        word: ["!what", "!ingredients", "?potion", "?life", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 111,
        answer: "All I can tell you is that you need three rare flowers to mix the Potion of Life.",
        special: 0,
    },
    Know {
        word: ["!why", "?want", "!potion", "?life", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 111,
        answer: "I'm sick. The Potion of Life would cure me.",
        special: 0,
    },
    Know {
        word: ["!where", "!potion", "?life", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 111,
        answer: "I don't think you can find the Potion of life somewhere. You'll have to create it.",
        special: 0,
    },
    Know {
        word: ["!how", "?first", "?door", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_GROLM,
        temp: 114,
        answer: "You need a key to get through the first door in the Grolm Gorge.",
        special: 0,
    },
    Know {
        word: ["!how", "!second", "?door", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 75,
        area: AR_GROLM,
        temp: 114,
        answer: "You need a crown to get through the second door in the Grolm Gorge.",
        special: 0,
    },
    Know {
        word: ["!how", "!third", "?door", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 75,
        area: AR_GROLM,
        temp: 114,
        answer: "You need a trident to get through the third door in the Grolm Gorge.",
        special: 0,
    },
    Know {
        word: ["!what", "!second", "?door", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 75,
        area: AR_GROLM,
        temp: 114,
        answer: "You need a crown to get through the second door in the Grolm Gorge.",
        special: 0,
    },
    Know {
        word: ["!what", "!third", "?door", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 75,
        area: AR_GROLM,
        temp: 114,
        answer: "You need a trident to get through the third door in the Grolm Gorge.",
        special: 0,
    },
    Know {
        word: ["!where", "!key", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_GROLM,
        temp: 114,
        answer: "The key for the first door in the Grolm Gorge is in a very hot place.",
        special: 0,
    },
    Know {
        word: ["!where", "!crown", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_GROLM,
        temp: 114,
        answer: "The crown from the Grolm Gorge? I'd expect the king wears it.",
        special: 0,
    },
    Know {
        word: ["!where", "!trident", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_GROLM,
        temp: 114,
        answer: "The trident from the Grolm Gorge? The Grolm Mages are said to use tridents.",
        special: 0,
    },
    Know {
        word: ["!what", "!key", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_GROLM,
        temp: 114,
        answer: "The key is used to open the first door.",
        special: 0,
    },
    Know {
        word: ["!what", "!crown", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_GROLM,
        temp: 114,
        answer: "The crown from the Grolm Gorge? It's used to open the second door.",
        special: 0,
    },
    Know {
        word: ["!what", "!trident", "?grolm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_GROLM,
        temp: 114,
        answer: "The trident from the Grolm Gorge? It's used to open the third door.",
        special: 0,
    },
    Know {
        word: ["!how", "?first", "?door", "?lizard", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 50,
        area: AR_LIZARD,
        temp: 162,
        answer: "You need a key to get through the first door in the Lizard Gorge.",
        special: 0,
    },
    Know {
        word: ["!how", "!second", "?door", "?lizard", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 75,
        area: AR_LIZARD,
        temp: 162,
        answer: "You need a key to get through the second door in the Lizard Gorge.",
        special: 0,
    },
    Know {
        word: ["!how", "!third", "?door", "?lizard", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 75,
        area: AR_LIZARD,
        temp: 162,
        answer: "You need a key to get through the third door in the Lizard Gorge.",
        special: 0,
    },
    Know {
        word: ["!where", "!key", "?lizard", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_LIZARD,
        temp: 162,
        answer: "The Merchants here will give you the keys for special items. Go to them to learn which items you need.",
        special: 0,
    },
    Know {
        word: ["!where", "!coconut", "?lizard", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_LIZARD,
        temp: 162,
        answer: "The coconut? Well, coconuts grow in trees, you know?",
        special: 0,
    },
    Know {
        word: ["!where", "!potion", "?agility", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_LIZARD,
        temp: 162,
        answer: "You have to mix the Potion of Superior Agility from some flower which grow here.",
        special: 0,
    },
    Know {
        word: ["!where", "!teeth", "?lizard", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_LIZARD,
        temp: 162,
        answer: "Lizard's Teeth? I'd assume they have them in their mouths.",
        special: 0,
    },
    Know {
        word: ["!how", "?teeth", "!necklace", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_LIZARD,
        temp: 162,
        answer: "To create the Lizard's Teeth Necklace, you need a leather string and teeth. One of the Merchants sells leather strings.",
        special: 0,
    },
    Know {
        word: ["?ratling", "!eye", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "Yes. I need them to create a very powerful stimulant. If you want to help me, buy a collector in Damor's shop and bring me a full set of Ratling's Eyes.",
        special: 0,
    },
    Know {
        word: ["!ratling", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "The Ratlings live below the city, in the Underground. They look like humans, except for the head, which resembles that of a rat. Be careful, some of the are very strong, and all of them can see in the dark.",
        special: 0,
    },
    Know {
        word: ["!stimulant", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "The stimulant will be extremely powerful. I'll be able to create two potions of it. You'll get one of them as payment.",
        special: 0,
    },
    Know {
        word: ["!potion", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "The potion will be extremely powerful stimulant. I'll be able to create two potions of it. You'll get one of them as payment.",
        special: 0,
    },
    Know {
        word: ["!payment", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "I can create two potions from a complete set of eyes. I'll give you one of them as payment.",
        special: 0,
    },
    Know {
        word: ["!how", "powerful", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "Very.",
        special: 0,
    },
    Know {
        word: ["!underground", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "The City Guards have recently discovered some holes in the ground of several buildings. They lead into a maze of rooms and corridors. It seems the thieves are using them too.",
        special: 0,
    },
    Know {
        word: ["!thief", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "A thief was trying to sell information about Azraels Helmet. A City Guard was chasing him, but he vanished in the Thief House. Later searches showed he used a hidden hole in the floor to escape.",
        special: 0,
    },
    Know {
        word: ["!azrael", "?helm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "Lord Azrael of Aston once ruled this city. But he vanished during a fight in his castle. He possesed a powerful helmet, the Helm of Shadows.",
        special: 0,
    },
    Know {
        word: ["!castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "It is now the Haunted Castle. After Azrael vanished, it was abandoned. Now it's inhabitated by ghosts, and some say they hear Azraels cry in there.",
        special: 0,
    },
    Know {
        word: ["!helm", "?shadow", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 246,
        answer: "Lord Azrael's famous helmet, the Helm of Shadows. It's enhanced with powerful magic.",
        special: 0,
    },
    Know {
        word: ["?ratling", "!eye", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 343,
        answer: "Yes. I need it to complete my collection. Robin wants a full set and he promised be a powerful potion in exchange.",
        special: 0,
    },
    Know {
        word: ["!ratling", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 343,
        answer: "The Ratlings live below the city, in the Underground. They look like humans, except for the head, which resembles that of a rat. Be careful, some of the are very strong, and all of them can see in the dark.",
        special: 0,
    },
    Know {
        word: ["!underground", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 343,
        answer: "The City Guards have recently discovered some holes in the ground of several buildings. They lead into a maze of rooms and corridors. It seems the thieves are using them too.",
        special: 0,
    },
    Know {
        word: ["!thief", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 343,
        answer: "A thief was trying to sell information about Azraels Helmet. A City Guard was chasing him, but he vanished in the Thief House. Later searches showed he used a hidden hole in the floor to escape.",
        special: 0,
    },
    Know {
        word: ["!azrael", "?helm", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 343,
        answer: "Lord Azrael of Aston once ruled this city. But he vanished during a fight in his castle. He possesed a powerful helmet, the Helm of Shadows.",
        special: 0,
    },
    Know {
        word: ["!castle", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 343,
        answer: "It is now the Haunted Castle. After Azrael vanished, it was abandoned. Now it's inhabitated by ghosts, and some say they hear Azraels cry in there.",
        special: 0,
    },
    Know {
        word: ["!helm", "?shadow", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 100,
        area: AR_UNDER_I,
        temp: 343,
        answer: "Lord Azrael's famous helmet, the Helm of Shadows. It's enhanced with powerful magic.",
        special: 0,
    },
    Know {
        word: ["?what", "!bartering", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Bartering will help you to get better prices from merchants.",
        special: 0,
    },
    Know {
        word: ["?what", "!enchant", "!weapon", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Enchant Weapon is a magic spell. It will make your weapon stronger when you use it.",
        special: 0,
    },
    Know {
        word: ["?what", "!recall", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Recall is a magic spell. It will teleport you back to the Temple of Skua when you use it. But beware, there is a small delay between casting and teleport.",
        special: 0,
    },
    Know {
        word: ["?what", "!repair", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Repair? That's the ability to repair your equipment.",
        special: 0,
    },
    Know {
        word: ["?what", "!stun", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Stun is a magic spell. If you can overcome your target's Resistance, he'll be unable to move for a few seconds.",
        special: 0,
    },
    Know {
        word: ["?what", "!lockpicking", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Lock-Picking?. It's used to pick locks, you know?",
        special: 0,
    },
    Know {
        word: ["?what", "!identify", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Identify is a magic spell. It'll give you some information about an item or person.",
        special: 0,
    },
    Know {
        word: ["?what", "!resistance", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Resistance is used against magic spells. If you're good at it, it's much harder to Curse or Stun you.",
        special: 0,
    },
    Know {
        word: ["?what", "!bless", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Bless is a powerful spell. It increases all your abilities.",
        special: 0,
    },
    Know {
        word: ["?what", "!curse", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Curse is a powerful spell. It decreases all your abilities.",
        special: 0,
    },
    Know {
        word: ["?what", "!guardian", "!angel", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "The spell Guardian Angel will lessen the effects of death on you. You can buy it from Damor, in Aston.",
        special: 0,
    },
    Know {
        word: ["?what", "!heal", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Heal is a magic spell. You can use it to heal a persons injuries.",
        special: 0,
    },
    Know {
        word: ["?what", "!gate", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "The last gate of the Labyrinth.",
        special: 0,
    },
    Know {
        word: ["?what", "!labyrinth", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "The Labyrinth. It's a huge maze full of dangers. If you survive it, you'll become a Seyan'Du.",
        special: 0,
    },
    Know {
        word: ["?what", "!seyandu", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "The Seyan'Du are very powerful. They do not have the limitations other people have.",
        special: 0,
    },
    Know {
        word: ["?what", "!limitation", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "The Harakim are powerful sorcerers, the Templars strong fighters and the Mercenaries have a bit of both. But the Seyan'Du combine their abilities.",
        special: 0,
    },
    Know {
        word: ["?what", "!templar", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "The Templars are powerful fighters. But they're not very good with magic.",
        special: 0,
    },
    Know {
        word: ["?what", "!harakim", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "The Harakim are spellcasters. They don't fight very well.",
        special: 0,
    },
    Know {
        word: ["?what", "!mercenary", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "A Mercenary is both, a fighter and a spellcaster.",
        special: 0,
    },
    Know {
        word: ["!who", "!skua", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Skua is the god of justice and order. He fights a perpetual battle against the Purple One.",
        special: 0,
    },
    Know {
        word: ["!who", "!purple", "!one", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "The Purple One? He's the god of chaos and disorder.",
        special: 0,
    },
    Know {
        word: ["?what", "!order", "?purple", "?one", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_PURPLE,
        temp: 180,
        answer: "Our order, the Cult of the Purple One, does not believes in rules. Join us, and you can do whatever you want.",
        special: 0,
    },
    Know {
        word: ["?tell", "!order", "?purple", "?one", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_PURPLE,
        temp: 180,
        answer: "Our order, the Cult of the Purple One, does not believes in rules. Join us, and you can do whatever you want.",
        special: 0,
    },
    Know {
        word: ["?how", "!join", "?order", "?purple", "?one", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_PURPLE,
        temp: 180,
        answer: "If you join us, you will be able to kill your fellow players. But beware! Others can kill you as well, and this decision is irrevocable! Do you want to join?",
        special: 0,
    },
    Know {
        word: ["?what", "!happens", "!join", "?order", "?purple", "?one", "?", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_PURPLE,
        temp: 180,
        answer: "If you join us, you will be able to kill your fellow players. But beware! Others can kill you as well, and this decision is irrevocable! Do you want to join?",
        special: 0,
    },
    Know {
        word: ["!yes", "!join", "?want", "!", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_PURPLE,
        temp: 180,
        answer: "So be it. But you have to pass a test first: Kill me!",
        special: 0,
    },
    Know {
        word: ["!yes", "!", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_PURPLE,
        temp: 180,
        answer: "So be it. But you have to pass a test first: Kill me!",
        special: 0,
    },
    Know {
        word: ["!kill", "?you", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_PURPLE,
        temp: 180,
        answer: "Yes. To join, you have to kill me. Go ahead, you coward!",
        special: 0,
    },
    Know {
        word: ["!poem", "?first", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_KNIGHT,
        temp: 317,
        answer: "Where the sun rises in a clouded sky     A mere touch will reveal where hidden lie       A skull which, when enlighted, will give thee    A brave enemy and a precious key.",
        special: 0,
    },
    Know {
        word: ["!poem", "?second", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_KNIGHT,
        temp: 317,
        answer: "A dark sky, a large tree                 Weavers work in crimson                         The corner of which guides thee                  To key's holder, the lord's son.",
        special: 0,
    },
    Know {
        word: ["!second", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_KNIGHT,
        temp: 317,
        answer: "A dark sky, a large tree                 Weavers work in crimson                         The corner of which guides thee                 To key's holder, the lord's son.",
        special: 0,
    },
    Know {
        word: ["!next", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_KNIGHT,
        temp: 317,
        answer: "A dark sky, a large tree                 Weavers work in crimson                         The corner of which guides thee                  To key's holder, the lord's son.",
        special: 0,
    },
    Know {
        word: ["!other", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_KNIGHT,
        temp: 317,
        answer: "A dark sky, a large tree                 Weavers work in crimson                         The corner of which guides thee                  To key's holder, the lord's son.",
        special: 0,
    },
    Know {
        word: ["?ice", "!egg", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_NEST,
        temp: 615,
        answer: "I heard that the ice gargoyles guard an ice egg in their nest. I'd be most grateful if you could bring it to me. But hurry, before it melts!",
        special: 0,
    },
    Know {
        word: ["?ice", "!cloak", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_NEST,
        temp: 615,
        answer: "The Ice Cloak is a fine piece of armor, but it melts in due time. I can give you one if you obtain an ice egg for me.",
        special: 0,
    },
    Know {
        word: ["!how", "!are", "!you", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: HEALTH,
    },
    Know {
        word: ["!who", "!are", "!you", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: WHOAMI,
    },
    Know {
        word: ["!where", "!are", "!you", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: WHERE,
    },
    Know {
        word: ["!where", "!am", "!i", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: WHERE,
    },
    Know {
        word: ["!buy", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: SHOP,
    },
    Know {
        word: ["!sell", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: SHOP,
    },
    Know {
        word: ["!shop", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: SHOP,
    },
    Know {
        word: ["!exit", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Enter the backroom of a tavern to leave the game, %s.",
        special: 0,
    },
    Know {
        word: ["!hello", "!", "$", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: GREET,
    },
    Know {
        word: ["!bye", "!", "$", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "Goodbye, %s.",
        special: 0,
    },
    Know {
        word: ["!thank", "?you", "!", "$", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "You're welcome, %s.",
        special: 0,
    },
    Know {
        word: ["!thank", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "You're welcome, %s.",
        special: 0,
    },
    Know {
        word: ["!stop", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: CT_COMPANION,
        answer: "",
        special: STOP,
    },
    Know {
        word: ["!move", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: CT_COMPANION,
        answer: "",
        special: MOVE,
    },
    Know {
        word: ["!attack", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: CT_COMPANION,
        answer: "",
        special: ATTACK,
    },
    Know {
        word: ["!wait", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: CT_COMPANION,
        answer: "",
        special: WAIT,
    },
    Know {
        word: ["!follow", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: CT_COMPANION,
        answer: "",
        special: FOLLOW,
    },
    Know {
        word: ["!transfer", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: CT_COMPANION,
        answer: "",
        special: TRANSFER,
    },
    Know {
        word: ["!geronimo", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: CT_COMPANION,
        answer: "",
        special: SPELLINFO,
    },
    Know {
        word: ["!time", "!what", "?", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: 0,
        answer: "",
        special: TIME,
    },
    Know {
        word: ["!quiet", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 0,
        area: AR_GENERAL,
        temp: CT_COMPANION,
        answer: "",
        special: QUIET,
    },
    Know {
        word: ["!riddle", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE1,
        temp: 899,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddles", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE1,
        temp: 899,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddle", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE2,
        temp: 905,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddles", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE2,
        temp: 905,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddle", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE3,
        temp: 911,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddles", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE3,
        temp: 911,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddle", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE4,
        temp: 912,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddles", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE4,
        temp: 912,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddle", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE5,
        temp: 913,
        answer: RIDDLE_TEXT,
        special: 0,
    },
    Know {
        word: ["!riddles", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        value: 10,
        area: AR_RIDDLE5,
        temp: 913,
        answer: RIDDLE_TEXT,
        special: 0,
    },
];

pub fn obey(cn: usize, co: usize) -> i32 {
    0
}

pub fn answer_spellinfo(cn: usize, co: usize) {}

pub fn answer_transfer(cn: usize, co: usize) {}

pub fn answer_follow(cn: usize, co: usize) {}

pub fn answer_wait(cn: usize, co: usize) {}

pub fn answer_stop(cn: usize, co: usize) {}

pub fn answer_move(cn: usize, co: usize) {}

pub fn answer_attack(cn: usize, co: usize, text: &str) {}

pub fn answer_quiet(cn: usize, co: usize) {}

pub fn answer_health(cn: usize, co: usize) {}

pub fn answer_shop(cn: usize, co: usize) {}

pub fn answer_greeting(cn: usize, co: usize) {}

pub fn answer_whoami(cn: usize, co: usize) {}

pub fn answer_where(cn: usize, co: usize) {}

pub fn answer_time(cn: usize, co: usize) {}

pub fn stronghold_points(cn: usize) -> i32 {
    0
}

pub fn stronghold_exp_per_pt(cn: usize) -> i32 {
    0
}

pub fn answer_points(cn: usize, co: usize, know_idx: usize) {}

pub fn answer_buygold(cn: usize, co: usize) {}

pub fn answer_buyhealth(cn: usize, co: usize) {}

pub fn answer_buymana(cn: usize, co: usize) {}

pub fn answer_buyexp(cn: usize, co: usize) {}

pub fn special_answer(cn: usize, co: usize, special: i32, word: &str, know_idx: usize) {}

pub fn npc_hear(cn: usize, co: usize, text: &str) {}
